### ISSUE TITLE
OneWire/DS18B20 library

### ISSUE THREAD

**Issue by Skipper-is** [HelTecAutomation/ASR650x-Arduino#10]
Would be really great to have a library for the DS18B20 family of chips. I have tried to port the existing Arduino library, but haven't had any joy..

**Comment by raystream** [comment]
hi 
i have added a OneWire library to my fork.
it compiles but can not test it ore because i have sensors

**Comment by Heltec-Aaron-Lee** [comment]
Thank you for your enthusiasm @raystream :D

I will test the library if I can find a 18B20 sensor.

**Comment by Skipper-is** [comment]
I've got a whole box of them on my desk, I'll give it a whirl soon (am on training for the next 3 days, but after that! It if I find some time, before that!)

**Comment by Skipper-is** [comment]
Through testing yesterday, I could get the ready signal back from the device, and transmit the search command (0xF0? I can't remember now...) But there was no response, I suspect it was in the switching from output to input rapidly, it was giving problems

**Comment by raystream** [comment]
i will get myself an DS18B20  and make some tests

**Comment by Skipper-is** [comment]
Have you added the ASR650 to the OneWire_direct_gpio.h file?

**Comment by Skipper-is** [comment]
![image](https://user-images.githubusercontent.com/28678069/67891225-16ca0200-fb4a-11e9-90fa-250a90b69c7e.png)
No joy with the library I'm afraid. It is doing a bit of a search (F0), but there are no responses, I wonder whether the device isn't switching to input, and is therefore over-riding the response from the DS18B20

**Comment by joergkeller** [comment]
I've got the OneWire/DallasTemperature libraries compiled, but with the same result: There is no sensor listed after search. The same wiring (with pullup resistor) and the same libraries worked with an Uno and Dragino Mini board.
@Skipper-is you asked about the OneWire_direct_gpio.h file. How/what did you enter there? The compiler currently does not define any architecture or board settings, so the library uses the default part.

**Comment by joergkeller** [comment]
Just retested with the provided OneWire library and DS18x20_Temperature example in the master branch - no sensor found.

**Comment by Skipper-is** [comment]
I didn't. That is partially what tripped me up. The Uno (and I am assuming all microcontrollers) have an internal port register. On the Uno, GPIO pins 0-7 are on the PORTD register, and you can use a bitmask, and bitwise operators to specify read/write modes, and Hi/Low settings. The advantage of this is to cycle signals really rapidly. 
I assume it is possible to do without the register, but I don't know how... For that we'd need to add something to the direct_gpio.h file I suspect. But that is beyond my ability!

**Comment by joergkeller** [comment]
That is also my understanding. The fallback already uses digitalRead/write/pinMode, but that is probably much slower.

**Comment by joergkeller** [comment]
I think I've found the solution. There are macros provided to directly modify the GPIO pins (CY_SYS_PINS_READ_PIN/CY_SYS_PINS_CLEAR_PIN/CY_SYS_PINS_SET_PIN/CY_SYS_PINS_SET_DRIVE_MODE). With some pointer arithmetic the OneWire library can directly use these.

Side note: Why is (a copy of) OneWire included in that project? Here it comes handy to quickly fix the issue but why not rely on the original OneWire library to be directly used by projects?

**Comment by raystream** [comment]
That is why the library is copied, to adopt it for using with the ASR6501 ;-)

Do you have a running version?
Would be great if you could make a pull request with the needed changes.

**Comment by raystream** [comment]
just tested it and it works like a charm.

thank you @joergkeller

**Comment by Skipper-is** [comment]
Can confirm, it is working:
`18:40:28.362 -> ROM = 28 4D 43 79 97 5 3 F2
18:40:28.395 ->   Chip = DS18B20
18:40:29.447 ->   Data = 1 3D 1 55 5 7F A5 81 66 8  CRC=8
18:40:29.481 ->   Temperature = 19.81 Celsius, 67.66 Fahrenheit
`
Great work!
