### ISSUE TITLE
about GPIO 0/5/4 location and pinout diagram

### ISSUE THREAD

**Issue by KunYi** [HelTecAutomation/ASR650x-Arduino#102]
HTCC-AB01 pin-out diagram  show the below
but schematic and physical board show 
- GPIO 0
- GPIO 5
- GPIO 4
not 
- GPIO 0
- GPIO 4
- GPIO 5
![image](https://user-images.githubusercontent.com/2186922/83114446-8a8db680-a0fb-11ea-849e-b39cc8ed3a33.png)

**Comment by Luckybuyu** [comment]
Now the pin-out diagram has been modified, please click this link to view.
[https://resource.heltec.cn/download/CubeCell/HTCC-AB01/HTCC-AB01_PinoutDiagram.pdf](https://resource.heltec.cn/download/CubeCell/HTCC-AB01/HTCC-AB01_PinoutDiagram.pdf)

**Comment by KunYi** [comment]
@Luckybuyu Thank you!
