### ISSUE TITLE
[BUG] No LoRa examples

### ISSUE THREAD

**Issue by IoTopenTech** [HelTecAutomation/ASR650x-Arduino#103]
Hi, I have installed the board manager in Arduino 1.8.10, but there is no LoRa category in examples
![imagen](https://user-images.githubusercontent.com/52624907/83259218-f0d80f00-a1b7-11ea-9583-38aafebe669b.png)

**Comment by Heltec-Aaron-Lee** [comment]
Seems every thing is normal at my side:
![image](https://user-images.githubusercontent.com/32860565/83354382-e621a380-a38a-11ea-96a4-5a678b5297c4.png)

Do you have another library named "LoRa"?

**Comment by IoTopenTech** [comment]
Yes, that is the problem... I had another librart named LoRA.
Thanks.

**Comment by JuriShalkin** [comment]
> Yes, that is the problem... I had another librart named LoRA.
> Thanks.

How did you solve this problem? I also have no examples of onewire.
