### ISSUE TITLE
Support for platformio coming?

### ISSUE THREAD

**Issue by prgazevedo** [HelTecAutomation/ASR650x-Arduino#11]
Hello,

Are you planning to add support to the board in platformio?
https://docs.platformio.org/en/latest/platforms/creating_board.html

Thanks

**Comment by Skipper-is** [comment]
I'd like to see it added to PlatformIO, always nice to have other IDE options!

**Comment by raystream** [comment]
i use vscode without problems.
its much better than the arduino ide.

and you can use sloeber.

**Comment by bertrik** [comment]
I'm also very much a platformio fan, I am happy to test support / help with getting it supported in platformio.

**Comment by raystream** [comment]
there is allready an issue opened in the platform.io github repository:

https://github.com/platformio/platformio-core/issues/3078

**Comment by lnlp** [comment]
It seems that work on this will now actually be started.
Looking forward to its availability. 🙂

**Comment by irukard** [comment]
Any update?

**Comment by wasn-eu** [comment]
https://github.com/HelTecAutomation/platform-asrmicro

**Comment by lnlp** [comment]
'Empty repository created.'
That's sort of an update but without much information.

**Comment by bertrik** [comment]
It works for me now, see https://github.com/platformio/platformio-core/issues/3078
I have a basic (empty) platformio project at
https://github.com/bertrik/cubecelldemo/blob/master/cubecelldemo.ino

It compiles, uploads and runs with
  pio run -t upload

This ticket can be closed I think

**Comment by lnlp** [comment]
And any related possible issues can now be reported in its own repository: https://github.com/HelTecAutomation/platform-asrmicro650x

**Comment by Heltec-Aaron-Lee** [comment]
https://github.com/HelTecAutomation/platform-asrmicro650x
