### ISSUE TITLE
ARDUINO define missing

### ISSUE THREAD

**Issue by eiten** [HelTecAutomation/ASR650x-Arduino#119]
Many libs depend on the ARDUINO define to figure out what the api is or which headers to include. Example:
```C++
#if ARDUINO >= 100
#include "Arduino.h"
#include "Print.h"
#else
#include "WProgram.h"
#endif
```
This define is missing in ASR650x-"Arduino". Please fix, I assume it should be 10805.

**Comment by gazzyt** [comment]
Just ran into this issue myself today.

**Comment by gazzyt** [comment]
I had v0.0.3 of this installed for some reason. Updating to v1.0.0 fixed this for me

**Comment by eiten** [comment]
Well, i have 1.0.0 installed on PlatformIO where this does not work

**Comment by eiten** [comment]
I gotta correct myself. It's working in Arduino IDE, not working in Platform.io

**Comment by tuxphone** [comment]
You can circumvent the problem with adding the following line to platform.io:

`build_flags = -D ARDUINO=100`

**Comment by Heltec-Aaron-Lee** [comment]
Now have V1.1.1 release, did you try that?
![image](https://user-images.githubusercontent.com/32860565/93583480-80f3cb80-f9d6-11ea-9e0b-7b49ae235868.png)
