### ISSUE TITLE
SPIx.beginTransaction not Arduino compatible

### ISSUE THREAD

**Issue by eiten** [HelTecAutomation/ASR650x-Arduino#120]
Hello,
Arduino is SPI.beginTransaction(SPISettings), where ASR650x it is SPIx.beginTransaction(void). Please fix.
Regards, Edi

**Comment by Heltec-Aaron-Lee** [comment]
Thanks, we will fix it in a few days

**Comment by Heltec-Aaron-Lee** [comment]
Hi, we have fixed SPI.beginTransaction(SPISettings).

**Comment by eiten** [comment]
Perfect! Thanks!
