### ISSUE TITLE
boardInitMcu() sets VBAT_ADC_CTL at HIGH level on HTCC-AB02S (GPS) 

### ISSUE THREAD

**Issue by lyusupov** [HelTecAutomation/ASR650x-Arduino#129]
This is [the code](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/cores/asr650x/board/src/asr_board.c#L468):

```
#if defined(CubeCell_Board)||defined(CubeCell_Capsule)||defined(CubeCell_BoardPlus)||defined(CubeCell_GPS)||defined(CubeCell_HalfAA)
    pinMode(Vext,OUTPUT);
    digitalWrite(Vext,HIGH);
    pinMode(VBAT_ADC_CTL,OUTPUT);
    digitalWrite(VBAT_ADC_CTL,HIGH);
#endif
```

And this is an  excerpt from schematics:

![image](https://user-images.githubusercontent.com/5849637/92126330-b7dbb600-ee08-11ea-844b-5e4734ec61b7.png)

When VBAT_ADC_CTL is HIGH and USER BUTTON is pushed down - **this applies high stress load on the MCU's GPIO pin**.

We can see that a 10K pullup resistor is already connected to VBAT_ADC_CTL wire.
So it has little or no sense to intentionally force the pin into HIGH state.

**It looks much more safe to set the VBAT_ADC_CTL pin into INPUT (or OD_HI) state at boot time** like this: 

```
pinMode(VBAT_ADC_CTL, INPUT);
```
or that:

```
pinMode(VBAT_ADC_CTL, OD_HI);
```

**Comment by nickkl** [comment]
Hi,
I have AM02 and I want to use ADC to examine if the battery has low power.
I'm not sure if I have to put some resistors before pin number 2 or just simply connect V_BAT to it.
also, by VBAT_ADC_CTL you mean GPIO7? if I want to use it for wake up from interrupt is won't be a problem?
can I use other GPIO for wake up from interrupt?
thanks a lot!!
