### ISSUE TITLE
Vext power line instability

### ISSUE THREAD

**Issue by Securethingsuk** [HelTecAutomation/ASR650x-Arduino#13]
It should be noted  that Vext power line for sensors is not stable after it is turned on!  and therefore to get some scripts working in the library such as the I2C scan in Basic ,  I have had to  Add delay as Below  I would recommend that this is added in all cases such as :

pinMode(Vext,OUTPUT);
digitalWrite(Vext,LOW);//set vext to high
**delay(500);// To allow the Powerline to settle 100-500 seems ok** 
Prior to calling the following  as the I2C SDA and SCL  line will not be stable

Serial.begin(115200);
  Wire.begin();

**Comment by Heltec-Aaron-Lee** [comment]
If Vext's load circuit has a large capacitance, the delay is very important.

Thanks for your update. I will update the code.
