### ISSUE TITLE
Missing AT_user_check

### ISSUE THREAD

**Issue by aparcar** [HelTecAutomation/ASR650x-Arduino#130]
The [AT_Command](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/libraries/LoRa/examples/AT_Command/AT_Command.ino) no longer contains the user specific `AT_user_check` method, this should be re-added for clarity.

**Comment by Heltec-Aaron-Lee** [comment]
What's the function of `AT_user_check`? Can you please provide some more information?

**Comment by aparcar** [comment]
Older revisions have that function but it was removed at some point 

https://github.com/HelTecAutomation/ASR650x-Arduino/commit/897da305ed93b18c7aae3f673e9b7d4793c32612#diff-7b33afbac0d26ba044dfcf3bfa70524b672ed70cdfd0d26c72147e45d2118a75R72-R84

**Comment by aparcar** [comment]
The user_command was added again in one of the latest commits.
