### ISSUE TITLE
No signal on Tx1 pin when CubeCell-GPS is powered from battery

### ISSUE THREAD

**Issue by lyusupov** [HelTecAutomation/ASR650x-Arduino#132]
Hardware: **HTCC-AB02S**
Software:  **ASR650x-Arduino V1.1.0**

Test sketch:

```
#include <Wire.h>
#include "cubecell_SSD1306Wire.h"

SSD1306Wire  display(0x3c, 500000, I2C_NUM_0,GEOMETRY_128_64,GPIO10 );

void setup() {
  Serial.begin(38400);
  Serial.println();

  Serial.println("Boot: PASSED");

  pinMode(Vext,OUTPUT);
  digitalWrite(Vext, LOW);

  delay(100);

  display.init();

  display.clear();
  display.setFont(ArialMT_Plain_24);
  display.setTextAlignment(TEXT_ALIGN_CENTER);
  display.drawString(64, 22, "ON");
  display.display();

}

void loop() {

  Serial.println("Test of default UART output");

  delay(100);
}
```

Oscilloscope's probe is connected to Tx1 pad:

![image](https://user-images.githubusercontent.com/5849637/92465980-107bcc00-f1d8-11ea-806f-3598d26c9d60.png)

When **the CubeCell is powered over microUSB** - everything is fine:

![image](https://user-images.githubusercontent.com/5849637/92466338-a0217a80-f1d8-11ea-9aaf-d119d4bfcdd9.png)

However, when the same test is running on the board, **powered by a 3.7V Li-Po battery cell** - there is no proper signal detected on the Tx1 pad:

![image](https://user-images.githubusercontent.com/5849637/92466595-ff7f8a80-f1d8-11ea-9bf9-f35106bf7546.png)

If I touch the probe with my finger, the scope indicates that the pad is in high impedance state:

![image](https://user-images.githubusercontent.com/5849637/92466763-45d4e980-f1d9-11ea-96e0-1b73a267dca6.png)

Rest of HTCC-AB02S hardware (**including Rx2/Tx2** Air530 GNSS pins) is operating nicely from the battery power.

**Comment by 15883893721** [comment]
hi,

We got the result. This was what we designed for low power consumption.
The situation is roughly like this:
When USB is powered, the serial port chip CP2102 will be powered on, and RX1 will be pulled to a high level . When you use this statement “Serial.begin();” in your code, the level of RX1 will be automatically detected. If RX1 is high, the serial port will be opened, so TX1 can The waveform is detected.

When only battery powered, cp2102 is not poweredand RX1 is not powered on either. The serial port is not started, RX1 has no waveform.

One of the solutions: Before the system starts (only battery power supply), the hardware method is to set RX1 to high level.

**Comment by lyusupov** [comment]
Good. Thank you for your explaination! Actually, this is close to that I expected to read.

> This was what we designed for low power consumption.

Have you **intentionally** designed that way ? 😄 
If it is so - I doubt that it was best possible solution...

Designer should be aware that user would like (and have a right) to connect further devices to the UART0 pins, such as Bluetooth/BLE/Wi-Fi or other bridge.

Ok. Could you, please, suggest 'software only' solutions first to fix this issue?
As an example, if I do:

```
pinmode(UART_RX1, OUTPUT);
digitalWrite(UART_RX1, HIGH);
Serial.begin(38400);
```
&nbsp;- this will NOT work as expected, right?

Next one is a 'hardware solution'. If I'll connect **external pullup** resistor to the Rx1 pin - it will work, right ?
If so, should we consider to add the pullup resistor (connected to, say, software-contolled **Vext** power supply) in further revisions of the CubeCell-GPS board ?

**Comment by lyusupov** [comment]
Ok, **disregard my first question** - I see your picture attached to the CubeCell forum answer...

**Comment by lyusupov** [comment]
I suppose that we should find a way to make somehow [this auto-sensing code](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/cores/asr650x/Serial/HardwareSerial.cpp#L36) optional... Shouldn't we ?

```
if(digitalRead(UART_RX)==UART_RX_LEVEL)//uart start when uart chip powered
```

**Comment by 15883893721** [comment]
![图片](https://user-images.githubusercontent.com/52631482/92593579-ec051a00-f2d3-11ea-8876-c67c4cf1d6ee.png)

Software method： Block the "if judgment" in the picture

**Comment by 15883893721** [comment]
C:\Users\admin\Documents\Arduino\hardware\CubeCell\ASR650x-Arduino\cores\asr650x\Serial

**Comment by 15883893721** [comment]
> 
> 
> I suppose that we should find a way to make somehow [this auto-sensing code](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/cores/asr650x/Serial/HardwareSerial.cpp#L36) optional... Shouldn't we ?
> 
> ```
> if(digitalRead(UART_RX)==UART_RX_LEVEL)//uart start when uart chip powered
> ```

yes， this is a good idea
