### ISSUE TITLE
Disable Automatic Low-Power

### ISSUE THREAD

**Issue by els14029** [HelTecAutomation/ASR650x-Arduino#133]
How to disable AutoLowPower permanently ? Because when after use AT Command; example AT+OTAA=? for 10s AutoLowPower will be shown and i must WakeUp First. I can handle with AT+AutoLPM=0 to disable automatic low power but EEPROM/flash write most likely it will last for some time? I'm afraid it will suddenly break the module

**Comment by Heltec-Aaron-Lee** [comment]
This function had added in the newest AT command list:
![image](https://user-images.githubusercontent.com/32860565/93583130-05921a00-f9d6-11ea-9ed8-265f1e43cc19.png)
