### ISSUE TITLE
AT Commands

### ISSUE THREAD

**Issue by raystream** [HelTecAutomation/ASR650x-Arduino#18]
would be great if these 2 AT commands could be implementet:

enable/disable LED
disable AT Commands

perhabs there could be an option to enable AT commands with the usr button after disabling it with AT command.

**Comment by Heltec-Aaron-Lee** [comment]
The factory AT command only suitable for HTCC-AM01, it's don't have RGB light default.

The AT command examples in Arduino, users can choose options in Arduino IDE menu:

![image](https://user-images.githubusercontent.com/32860565/68928817-f5ae1600-07c5-11ea-84b0-17a80431ad6f.png)
