### ISSUE TITLE
Support for sub band choice within AU915

### ISSUE THREAD

**Issue by mutton74** [HelTecAutomation/ASR650x-Arduino#19]
I am trying to use the cubecell with LoRaWAN on The Things Network (TTN).

At the moment the join process takes a long time and receiving messages is unreliable.

I believe that this is due to TTN using the second sub band (Channels 8-15) out of the 64 channels available and this library seems to be set to the first sub band (Channels 0-7)

Taken from cores/asr650x/kernel/protocols/lorawan/lora/mac/region/RegionAU915.c

`            // Channels
            // 125 kHz channels
            for( uint8_t i = 0; i < AU915_MAX_NB_CHANNELS - 8; i++ )
            {
                Channels[i].Frequency = 915200000 + i * 200000;
                Channels[i].DrRange.Value = ( DR_5 << 4 ) | DR_0;
                Channels[i].Band = 0;
            }
            // 500 kHz channels
            for( uint8_t i = AU915_MAX_NB_CHANNELS - 8; i < AU915_MAX_NB_CHANNELS; i++ )
            {
                Channels[i].Frequency = 915900000 + ( i - ( AU915_MAX_NB_CHANNELS - 8 ) ) * 1600000;
                Channels[i].DrRange.Value = ( DR_6 << 4 ) | DR_6;
                Channels[i].Band = 0;
            }`

TTN uses [these channels](https://www.thethingsnetwork.org/docs/lorawan/frequency-plans.html#au915-928)

**Comment by raystream** [comment]
you can change it in the RegionAU915.c file.

`Channels[i].Frequency = 916800000 + i * 200000;`

**Comment by mutton74** [comment]
OK thanks I changed that and it does seem to join and send on the correct channels but it misses lots of (unconfirmed) uplinks.

![image](https://user-images.githubusercontent.com/30203771/68943841-07a8ac80-07f8-11ea-8d0d-e8a3ed6cc7bf.png)

It has perfect reception  to a confirmed working gateway on TTN (11.5 SNR)

Any other ideas to get it more reliable?

**Comment by raystream** [comment]
the change i provided only changed the uplink frequencies for the 125kHz channels but not for the 500kHz channels and the downlink.

**Comment by raystream** [comment]
tried my best to add a new compiler option for the frequency band AU915_SB2

**Comment by mutton74** [comment]
Sorry not much different - if there is anything I can do to help diagnose please let me know

This what I am seeing
![image](https://user-images.githubusercontent.com/30203771/69479062-06553080-0e45-11ea-96ec-110ecd759592.png)

**Comment by raystream** [comment]
hope i have fixed the problem.

**Comment by mutton74** [comment]
seeing this now
![image](https://user-images.githubusercontent.com/30203771/69485136-f65e4080-0e86-11ea-8ddf-6aa3ed393183.png)

**Comment by raystream** [comment]
Please post the frequencies used for the correct uplinks and downlinks in your screenshot.
Whats the dutycycle you have used?

**Comment by mutton74** [comment]
15 secs duty cycle

Join attempt
  "lora": {
    "spreading_factor": 12,
    "bandwidth": 500,
    "air_time": 288768000
  },
  "coding_rate": "4/5",
  "timestamp": "2019-11-23T21:33:22.529Z",
  "frequency": 923300000

Count 6 - uplink
  "frequency": 917.8,
  "modulation": "LORA",
  "data_rate": "SF12BW125",
  "coding_rate": "4/5",

Count 10 uplink
  "frequency": 917.6,
  "modulation": "LORA",
  "data_rate": "SF12BW125",
  "coding_rate": "4/5",

Downlink frequencies (from gateway)
  "lora": {
    "spreading_factor": 12,
    "bandwidth": 500,
    "air_time": 329728000
  },
  "coding_rate": "4/5",
  "timestamp": "2019-11-23T21:36:58.628Z",
  "dev_addr": "26042457",
  "frequency": 923300000

**Comment by Bwooce** [comment]
There's an issue that was fixed in LoRaMac-node 4.4.2 that probably has some bearing here. Check out [this bit](https://github.com/HelTecAutomation/ASR650x-Arduino/commit/ca009e05d3256f1c641d286e5c116a3d22a918fb#diff-7a80f66ff4a76731d18748b5fc7203a5R425) and think about how many channels are in the mask -- only 8 right? So this function is likely failing when it gets called.

I think this is the source of the problems for OTAA but I've not been able to trace the flow yet (it's also possible that the channel list wasn't sent in the join response for AU915 for LoRaWAN 1.0.2 or something, I remember reading that somewhere it was a bit of an error in the spec). It's weird that it would work with ADR of course, which is why it's a good puzzle.

It also points to an easier way of implementing the sub-band restriction e.g.

` // Enabling 2nd block of 8 channels (8-15) + channel 65
  MibRequestConfirm_t mibReq;

  uint16_t channelMask[] = { 0xFF00, 0x0000, 0x0000, 0x0000, 0x0002, 0x0000};
  mibReq.Type = MIB_CHANNELS_MASK;
  mibReq.Param.ChannelsMask = channelMask;
  LoRaMacMibSetRequestConfirm( &mibReq );`

[as well as removing that 20+ channel bit of code]

I'm testing this right now, and paring it back to discover if it's only required once (post-join) or more frequently (no pun intended). There were other regional changes in 4.4.2 that would be great to roll-forward too though, but quite an API change as well sadly.

**Comment by Heltec-Aaron-Lee** [comment]
Hi guys, do not need so complicated at all. LoRaWAN is a complete protocol, and TTN has good support for it.

**Now, let's look into the LoRaWAN protocol firstly, I think this sentence is clear enough:**
![image](https://user-images.githubusercontent.com/32860565/69524153-64e2f180-0fa0-11ea-9fea-407424c093d6.png)

**Then, let's look into our code:** (in LoRaWan_APP.cpp file)
![image](https://user-images.githubusercontent.com/32860565/69524338-c0ad7a80-0fa0-11ea-82fa-d250ebe80e14.png)
Here are 5 arrays defined all channels of LoRaWAN protocol for AU915. In the channelsMaskTemp[0], 0x00FF means use the first 0~7 channels, they are 915.2MHz, 915.4MHz, 915.6MHz … 916.6MHz. When you set the value to 0xFF00, it means the upload channels changed to 8~15, they are 916.8MHz, 917.0MHz … 918.2MHz. More detail... see the below picture (Forgive me for my bad English writing😄):
![image](https://user-images.githubusercontent.com/32860565/69524784-cbb4da80-0fa1-11ea-98d4-4d2774b42eea.png)

**Then, let's look back to the TTN's uplink/downlink define for AU915:**
[https://www.thethingsnetwork.org/docs/lorawan/frequency-plans.html](https://www.thethingsnetwork.org/docs/lorawan/frequency-plans.html)
![image](https://user-images.githubusercontent.com/32860565/69525025-3534e900-0fa2-11ea-9408-58b918c31b18.png)

Generally speaking... we just need to change the `channelsMaskTemp[0]=0xFF00;`, the uplink frequency will be changed to TTN supported.

BTW. Also, the listening frequency in your LoRa gateway must the same as the TTN server. it's defined in your gateway's gloable_conf.json file.

**Comment by Bwooce** [comment]
Hey I agree Aaron.Lee, I think the mask change is all that's required. The additional complication that I've uncovered is the AU915 regional definition which (for the 4.4.1 release) insists on there being 20 channels for AU915 (only, this was an Australia specific thing). This is wrong and was changed in 4.4.2 but so was a lot of the API.

Check out the RegionAU915ChanMaskSet, the top few lines validate there should be 20 channels or it fails to do anything. I think that's what is happening here, see [this bit of code](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/635cee424d82074fc8dcc7835aad5d5279011976/cores/asr650x/kernel/protocols/lorawan/lora/mac/region/RegionAU915.c#L422)

RegionAU915ChanMaskSet is called eventually from your LoRaMacMibSetRequestConfirm call in your code, if you trace it all the way down.

**Comment by raystream** [comment]
thanks Aaron for your help.

Using compile Option AU915SB2 now uses the normal AU915 files and switches the channelMaskTemp in LoRaWAN_APP

**Comment by raystream** [comment]
Would be great if someone could test this fix.

**Comment by mutton74** [comment]
Ill give it a try (does it include Bwooce's suggestions above?) 

- on a side note trying to update the library from within Arduino times out, download is too slow, yet downloading a zip and unpacking it is fine

**Comment by mutton74** [comment]
Sorry might have got worse.

Does not join at all, just hangs trying, nothing seen on gateway, nothing in TTN Application and this is what Serial Monitor shows

![image](https://user-images.githubusercontent.com/30203771/69620307-e910a400-1088-11ea-81b9-3482e50f0b4b.png)

With regards to my gateway setup.

This gateway has been operating flawlessly for about 3 years with hundreds of nodes operating and tested on it over that time using a mixture of LMIC and Microchip AU915 code.

**Comment by Heltec-Aaron-Lee** [comment]
Can you please paste your gloable_conf.json file?

**Comment by mutton74** [comment]
[global_conf.txt](https://github.com/HelTecAutomation/ASR650x-Arduino/files/3891347/global_conf.txt)

just converted to TXT so it would attach here

**Comment by mutton74** [comment]
Using this installer from a TTN supporter

https://github.com/kersing/multitech-installer

**Comment by mutton74** [comment]
I will test again tonight as there seems to be some issues with the TTN routers, just to rule out any TTN/application issues.

**Comment by Heltec-Aaron-Lee** [comment]
@mutton74 Tomorrow I will test at my side.

**Comment by mutton74** [comment]
OK thanks, just to confirm, I tested it again on a TTN handler that is known to be working and same result

**Comment by Heltec-Aaron-Lee** [comment]
I did many tests tonight, the gateway is the HT-M02 made by us. 
![image](https://user-images.githubusercontent.com/32860565/69810568-2dd24180-1227-11ea-8349-384251f8e4a5.png)

 just simply fixed the `channelsMaskTemp[0] = 0xFF00;`, it's working stable after joined.
![image](https://user-images.githubusercontent.com/32860565/69811044-2ceddf80-1228-11ea-9212-9e59007888f2.png)
![image](https://user-images.githubusercontent.com/32860565/69811066-3a0ace80-1228-11ea-97b0-c87dcbd3e9a9.png)

This is my [global_conf.json](https://github.com/HelTecAutomation/lorasdk/blob/master/global_conf_AU915_TTN.json), it's almost the same with @mutton74 's

**Comment by Heltec-Aaron-Lee** [comment]
But this code still has a strange problem: not always join for the first time... I printed some debug info, shown the TX data been sent out more than one time, and some frequency not for AS915.
![image](https://user-images.githubusercontent.com/32860565/69814033-61fd3080-122e-11ea-91da-b254f7148932.png)

I also tested the SB2 define written by @raystream, it seems no data send out. Can I reset the code to the point before you add AU915_SB2 (Indeed I don't know how to remove one commit 😭)? I need to look into the original source code to fix this bug.

**Comment by raystream** [comment]
found a failure for using the Subband 2 and corrected it in

https://github.com/HelTecAutomation/ASR650x-Arduino/commit/07dac0dffdf576b5f9d032c4c55eda834d327085

the changes are in the compiled firmware to. just flash the firmware with the AU915SB2 setting again.
the actual firmware will be downloaded and flashed

**Comment by raystream** [comment]
> But this code still has a strange problem: not always join for the first time... I printed some debug info, shown the TX data been sent out more than one time, and some frequency not for AS915.
> ![image](https://user-images.githubusercontent.com/32860565/69814033-61fd3080-122e-11ea-91da-b254f7148932.png)
> 
> I also tested the SB2 define written by @raystream, it seems no data send out, but I didn't find any unsuitable. Hey, @raystream , can I reset the code to the point before you add AU915_SB2 (Indeed I don't know how to remove one commit 😭)? I need to look into the original source code to fix this bug. I think the problem is caused by some error initial config.


you can just type the following in your git bash (will make a new branch with the state before my commit):

git checkout -b before_AU915SB2 deaa4df65393d4239fc93675c9602e58be9070c5

or type the following to get to the state before my commit:

git reset --hard deaa4df65393d4239fc93675c9602e58be9070c5

to take back just that commit and hope there will be no conflicts you can try:

git revert deaa4df65393d4239fc93675c9602e58be9070c5

**Comment by raystream** [comment]
@mutton74 have you found time to test the new compiled AU915SB2 version or the recent github version here?

**Comment by mutton74** [comment]
I have just tested it and it attempts to jin but nothing seen on the gateway or the application

Keys checked twice to be sure

![board settings](https://user-images.githubusercontent.com/30203771/69895046-924ee700-1374-11ea-9f81-288499736426.jpg)

![Serial Output](https://user-images.githubusercontent.com/30203771/69895052-9b3fb880-1374-11ea-9e7f-cf2a62a0f2a8.jpg)

**Comment by Bwooce** [comment]
Hey Aaron Lee, did you make any progress? Need any help? (I know you've had some distractions)

**Comment by Heltec-Aaron-Lee** [comment]
@Bwooce Yes, we are still working on this. Found some problem in the AU915 code and trying to solve it.

**Comment by Heltec-Aaron-Lee** [comment]
Hi there

I found out the reason for the AU915 sub-band, the AU915 sub-band requires at least 20 125KHz channels... but normally, a gateway have 8 channels.
![image](https://user-images.githubusercontent.com/32860565/70538151-9660dd00-1b9c-11ea-9102-3fccd464b3fd.png)
![image](https://user-images.githubusercontent.com/32860565/70538106-83e6a380-1b9c-11ea-92a3-e4623abf1829.png)

But my network is too bad, I will push the code tomorrow when I'm back to my office.

**Comment by mutton74** [comment]
Have you had a chance to progress this any further?

Can I test anything for you again?

**Comment by raystream** [comment]
Had no time to look at it cause we are just now making our modular node ready for sale.
Hope to have time next week

**Comment by Heltec-Aaron-Lee** [comment]
I think this bug had been fixed already.
[https://heltec-automation-docs.readthedocs.io/en/latest/cubecell/sub_band_usage.html](https://heltec-automation-docs.readthedocs.io/en/latest/cubecell/sub_band_usage.html)

**Comment by mutton74** [comment]
No, this was the result from that suggestion - again just tested - same result


> Sorry might have got worse.
> 
> Does not join at all, just hangs trying, nothing seen on gateway, nothing in TTN Application and this is what Serial Monitor shows
> 
> ![image](https://user-images.githubusercontent.com/30203771/69620307-e910a400-1088-11ea-81b9-3482e50f0b4b.png)
> 
> With regards to my gateway setup.
> 
> This gateway has been operating flawlessly for about 3 years with hundreds of nodes operating and tested on it over that time using a mixture of LMIC and Microchip AU915 code.

**Comment by Bwooce** [comment]
Back from a bit of a break now. I've just moved from my hacked up 0.4 release of Cubecell to the HEAD and my board has gone from OTAA Joining okay to not joining (as per mutton74's results).

It just sits after Joining. It is transmitting (LED is going BLUE/~GREEN(YELLOW?)/RED ) but I'm not seeing it on my gateway. 

I'm not seeing the traffic on my gateway, and I was before, so this is a software issue somewhere. I'm going to be away from AU915 gateways for a week or so, but I'll have a dig around in the meantime.

**Comment by Bwooce** [comment]
I've compared my changes I did on r0.4 with the current HEAD and they're functionally ~equivalent. So this is a new problem introduced between then and now.

**Comment by Bwooce** [comment]
Resolved. 

Maybe it's just that I'm using OTAA now. Putting this function prior to LoraWAN.Join()  (I already had it prior to the subsequent LoRaWAN.Send()'s but I don't know if that's really required...hey it can't hurt).

@mutton74 mutton74 please try this? 

Use the current HEAD (not r0.0.4 release from the library manager), then add

`void setTTNBand() {`

`  Serial.println("setTTNBand");`

`  // Enabling only 2nd block of 8 channels (8-15) + channel 65`
 ` MibRequestConfirm_t mibReq;`

 ` uint16_t channelMask[] = { 0xFF00, 0x0000, 0x0000, 0x0000, 0x0002, 0x0000};`
 ` mibReq.Type = MIB_CHANNELS_MASK;`
 ` mibReq.Param.ChannelsMask = channelMask;`
 ` LoRaMacMibSetRequestConfirm( &mibReq );`

`}`
 
into your sketch and call it before LoRaWAN.Join() in the loop()? Works for me like a charm.

I think this is TTN-specific as they're only using those 8 channels (of 16? available), so I'm not sure if/how that should be wedged into the CubeCell code -- we should have an example though :-)

**Comment by mutton74** [comment]
PERFECT thanks @Bwooce 

I was beginning to doubt my setup - not sure why but there wasnt much left to try

Now to use this great little board

cheers
Paul

**Comment by wasn-eu** [comment]
@Bwooce 
and if you encapsulate it like this than you can have it in your code and it will only be active is you select the AU915 frequencyband:

     case DEVICE_STATE_JOIN:
      {
         #if (ACTIVE_REGION == 1)
         setSubBand2();
         #endif
         LoRaWAN.Join();
         break;
      }

and make a little function out of the code from @Bwooce :

    void setSubBand2() {
      Serial.println("setSubBand2");
      // Enabling only 2nd block of 8 channels (8-15) + channel 65
      MibRequestConfirm_t mibReq;
    
      uint16_t channelMask[] = { 0xFF00, 0x0000, 0x0000, 0x0000, 0x0002, 0x0000};
      mibReq.Type = MIB_CHANNELS_MASK;
      mibReq.Param.ChannelsMask = channelMask;
      LoRaMacMibSetRequestConfirm( &mibReq );
    }

**Comment by Heltec-Aaron-Lee** [comment]
Hope this make sense:
[http://community.heltec.cn/t/use-cubecell-and-m01-connect-to-ttn-au915-sub-band/1098](http://community.heltec.cn/t/use-cubecell-and-m01-connect-to-ttn-au915-sub-band/1098)

**Comment by mikemccauley** [comment]
My experience is that the setSubBand2 solution from @Bwooce works to let the OTAA join succeed, but subsequent uplink messages would not get to the gateway (Dragino LG308). I have to alter the global userChannelsMask like this:
uint16_t userChannelsMask[6] = { 0xFF00, 0x0000, 0x0000, 0x0000, 0x0002, 0x0000}; // AU915 subband 2

**Comment by MVaras** [comment]
For anyone who need the AU915 for Chile is uint16_t userChannelsMask[6] = { 0x00FF, 0x0000, 0x0000, 0x0000, 0x0001, 0x0000}; // AU915. Thanks for all you guys, this was very helpful.

**Comment by Hucksleyy91** [comment]
Can we get uint16_t userChannelsMask[6] = { 0x00FF, 0x0000, 0x0000, 0x0000, 0x0001, 0x0000};
for AU915 channels 40-47 ? as they have been updated

**Comment by Hucksleyy91** [comment]
> (

Hey mate im trying to get the 6th block of 8 channels for AU915 any chance you can help change this from SUBBAND 2 to 6 

uint16_t userChannelsMask[6] = { 0xFF00, 0x0000, 0x0000, 0x0000, 0x0002, 0x0000}; // AU915 subband 2

**Comment by MVaras** [comment]
Im not pretty sure but...

uint16_t userChannelsMask[6] = { 0x0000, 0x0000, 0xFF00, 0x0000, 0x0006, 0x0000}; // AU915 subband 6

**Comment by MVaras** [comment]
which channels are you using for RX and time delay?

AU915 SB6
500 kHz Uplink  69 911000000
500 kHz Downlink 5 926300000

Maybe change 6 to 5, because it has 0 to 7 channels
uint16_t userChannelsMask[6] = { 0x0000, 0x0000, 0xFF00, 0x0000, 0x0005, 0x0000}; // AU915 subband 6

**Comment by MVaras** [comment]
That frequencies seems odd (TX and RX), you need to change RX/TX conf (and maybe delay too)

TX on freq 924000000 Hz at DR 0
Event : Tx Done
RX on freq 925700000 Hz at DR 8
Event : Rx Done

Please check this (you have to adapt to AU915, because it is for US915) https://www.baranidesign.com/faq-articles/2019/4/23/lorawan-usa-frequencies-channels-and-sub-bands-for-iot-devices

**Comment by Hucksleyy91** [comment]
this is the repo
https://github.com/hkicko/CubeCell-GPS-Helium-Mapper/blob/master/src/main.cpp#L63

"AS923_AS1" Region works as i have tested,  but only at 16dbi, and 3dbm = double power
So for 14dbm difference it is 2x2x2x2x2=32 times more power 
https://docs.google.com/document/d/1AAZjdMomfmd_gUeGoqXlw9EOO4DrDHp-FIUJCmTRQ9s/edit#
