### ISSUE TITLE
Missing microsecondsToClockCycles() macro

### ISSUE THREAD

**Issue by joergkeller** [HelTecAutomation/ASR650x-Arduino#24]
Using the DHT library (by Adafruit, version 1.3.8, https://github.com/adafruit/DHT-sensor-library) created a compile error because the macro microsecondsToClockCycles() is missing in Arduino.h.

Adding this code to Arduino.h fixed the problem:
````
#define clockCyclesPerMicrosecond() ( 48L ) // clock cycle 48 MHz
#define clockCyclesToMicroseconds(a) ( (a) / clockCyclesPerMicrosecond() )
#define microsecondsToClockCycles(a) ( (a) * clockCyclesPerMicrosecond() )
````
I am using version 0.0.3, installed by the board manager on Arduino IDE 1.8.10.

**Comment by raystream** [comment]
added it in #40ce975b185b1981184db427c349b56973502de5
