### ISSUE TITLE
Where to solder Battery to a capsule?

### ISSUE THREAD

**Issue by raystream** [HelTecAutomation/ASR650x-Arduino#3]
where can i solder a battery in the upper half of the capsule where the antenna is?

**Comment by Heltec-Aaron-Lee** [comment]
We have sold batteries for Capsule, but due to transportation problems, sensors with integrated batteries cannot be shipped abroad. We will find a solution to this problem.

**Comment by raystream** [comment]
i know this.
in the datasheet is that there are solder pads for a battery.
i have a lipo here.
i only need to know where these solder pads for the battery are.

**Comment by solotaker** [comment]
it's here.
http://community.heltec.cn/t/cubecell-capsule-and-a-battery/385
