### ISSUE TITLE
Vext has the wrong voltage after LowPower_Handler() and wakeup

### ISSUE THREAD

**Issue by Bwooce** [HelTecAutomation/ASR650x-Arduino#35]
After going to sleep and waking up, Vext is off. That's probably expected. Turning it back on results in ~1.6-1.8v on the pin, not the expected 3.3v and this won't properly drive most devices.

[See this community discussion,](http://community.heltec.cn/t/lowpower-handler-function-on-the-cubecell-board/582/6) I've also experienced the same thing independently.

**Comment by Heltec-Aaron-Lee** [comment]
You had connect a sensor, right? That's because the current from the GPIO is inverted to Vext, which generates a certain voltage.
Please set the sensor's relevant GPIO to ANALOG while sleep mode.
for example:
`pinMode(GPIO0, ANALOG);`

**Comment by lnlp** [comment]
@Bwooce Do you mean you measured 1.6 to 1.8V on the Vext pin or on GPIO6?

@Heltec-Aaron-Lee If this is about GPIO6 then the Arduino Core should properly handle this before entering deepsleep, not the user sketch.
Can you please give more details about what you exactly mean with "GPIO is inverted to Vext" and "which generates a certain voltage"?
What difference would it make (technically) to set (before entering sleep) a GPIO to ANALOG  during sleep?

**Comment by eiten** [comment]
@lnlp it is common that ARM processors have the lowest power consumption of GPIO pins when they are configured as analog in. Itŝ the same with the STM32.
