### ISSUE TITLE
Respone to DevStatusReq

### ISSUE THREAD

**Issue by wasn-eu** [HelTecAutomation/ASR650x-Arduino#36]
it would be great if the CubeCell devices would response to the DevStatusReq request with battery level and link margin.

**Comment by Bwooce** [comment]
The [code is there](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/68c0714817930f07e5c3dc9955b081102bf4109f/cores/asr650x/loramac/mac/LoRaMac.c#L2203) are you sure it doesn't? TTNv2 doesn't/can't request it (to my knowledge) though. I suspect the SNR code needs some investigation, [see this LoRaMac issue](https://github.com/Lora-net/LoRaMac-node/issues/75) but I'm interested to know if it's trying at all?

**Comment by wasn-eu** [comment]
it works
