### ISSUE TITLE
DS18x20_Temperature OneWire example problem

### ISSUE THREAD

**Issue by Stone-Hedge** [HelTecAutomation/ASR650x-Arduino#38]
Hi @raystream and thank you for publishing the examples.

When I try to compile the DS18x20 example I get the following message.

```
Multiple libraries were found for "OneWire.h"
In file included from C:\Users\xxx\Documents\Arduino\cubecell_dsb18b20\cubecell_dsb18b20.ino:1:0:

 Used: C:\Users\dan\Documents\Arduino\libraries\OneWire
C:\Users\xxx\Documents\Arduino\libraries\OneWire/OneWire.h:15:52: fatal error: WProgram.h: No such file or directory

 Not used: C:\Users\xxx\AppData\Local\Arduino15\packages\CubeCell\hardware\CubeCell\0.0.4\libraries\OneWire
compilation terminated.

exit status 1
Error compiling for board CubeCell-Board.
```

Can you please tell me what I am doing wrong?

**Comment by raystream** [comment]
you get this error because the wrong library is used.
you can see that this library is used:
  C:\Users\xxx\Documents\Arduino\libraries\OneWire/OneWire.h
the right one is:
  C:\Users\xxx\AppData\Local\Arduino15\packages\CubeCell\hardware\CubeCell\0.0.4\libraries\OneWire

just delete the wrong library (C:\Users\xxx\Documents\Arduino\libraries\OneWire)

**Comment by raystream** [comment]
there is a general problem with the OneWire library with the 0.4.0 version.
fixing this is on my agenda but will take 1-2 weeks.

**Comment by mikenz** [comment]
Previous PRs fixed the compilation issue with DallasTemperature.h and https://github.com/HelTecAutomation/ASR650x-Arduino/pull/50 adds DallasTemperature examples.

**Comment by raystream** [comment]
thanks to @mikenz OneWire is now functional again.
Please use the GIT repository for your arduino IDE and not the one from the board manager
