### ISSUE TITLE
ccs811 library

### ISSUE THREAD

**Issue by raystream** [HelTecAutomation/ASR650x-Arduino#4]
when i use the example for the ccs811 i only get the following values:

CO2: 400 TVOC: 0

**Comment by solotaker** [comment]
Hello, I also found this problem,
And I found that the readings returned to normal after multiple sets of data.
I took a close look at the problem, which seems to be related to the initialization of the CSS811 sensor and seems to require a longer initialization wait time.
After testing, I found that **every time I wake up** the CSS811 again, I need to wait 5 seconds for the reading to be normal.
After that I will do more tests, thank you for your corrections.

**Comment by raystream** [comment]
the problem is that after each reset the ccs811 will calibrate itself.
to get consistent data the baseline has to be set in the library.

to do this the sensor has to be running for about 20minutes and then the baseline must be exported this baseline can be set in the library.

**Comment by raystream** [comment]
the set and get baseline functions are now in the CCS811 library.
ToDo:
  Find out how to store the baseline in a nonvolatile memory (maybe the sflash).

**Comment by raystream** [comment]
now the baseline is stored in the userflash
see MJMCU-8128 example
