### ISSUE TITLE
In ABP also confirmed is off BUT not working!

### ISSUE THREAD

**Issue by OstertagM** [HelTecAutomation/ASR650x-Arduino#44]
My configuration is:
```
Copyright @ 2019 Heltec Automation.All rights reserved.

AT Rev 0.5

+LORAWAN=1

+KeepNet=0
+OTAA=0
+Class=A
+ADR=1
+IsTxConfirmed=0
+AppPort=0
+DutyCycle=15000
+ConfirmedNbTrials=1

```
But no payload is sended:
![grafik](https://user-images.githubusercontent.com/26908656/71561364-dae1e900-2a75-11ea-9c92-e23423786a8d.png)
![grafik](https://user-images.githubusercontent.com/26908656/71561394-30b69100-2a76-11ea-9bd8-4531d93d1816.png)
OK Port 0 does not work :-)
![grafik](https://user-images.githubusercontent.com/26908656/71561484-33fe4c80-2a77-11ea-907c-81e58ee5e547.png)
But still confirmed

**Comment by wasn-eu** [comment]
can confirm this and it is a problem if the gateway sends data to more than one server.

**Comment by OstertagM** [comment]
OK. It seems that in AOTA it worked well.
Is it possible to send only sometimes an confirmed uplink. For checking if ttn gets the package.

**Comment by wasn-eu** [comment]
chirpstack server received the packages as unconfirmeddataup
only ttn server thinks that it is a confirmed one

**Comment by OstertagM** [comment]
Please correct it! I use TTN
