### ISSUE TITLE
JOIN accapt is not received by node capsulate!

### ISSUE THREAD

**Issue by OstertagM** [HelTecAutomation/ASR650x-Arduino#48]
I have made test yesterday. All was ok. Join after one try. Today now I can't what's wrong?
I use the original example of interrupt.
![grafik](https://user-images.githubusercontent.com/26908656/71623264-9cfed500-2bdb-11ea-8eab-581b3ce58066.png)
and some minutes later it worked. Could it be that an join did not work if it is connected to USB?
![grafik](https://user-images.githubusercontent.com/26908656/71623580-e8b27e00-2bdd-11ea-818e-e69ff8b7ae24.png)

**Comment by Heltec-Aaron-Lee** [comment]
Are you connected to TTN's server? TTN has a limit on the number of downlinks sent every day, can this be the reason?

**Comment by OstertagM** [comment]
Yes I connected it to TTN but as you can see in second picture timestamp there is no reason for this downlink limit. Because the acceptance was sended out. The picture you see is only from one node. 
I think it is an timing error or something. 
But I have no chance to Debug. 
Or can it switche some Debug to serials output on? 
This would be a good option. 
We should have the possibility to see when which state is achieved in microseconds. Or if something is received but wrong crc or something.

**Comment by raystream** [comment]
what gateway are you using?
i had this issue with the ttn indoor gateway every day and needed to restart it.
With my mikrotik based gateways or the heltec gateways i never had this issue.

**Comment by OstertagM** [comment]
Yes it is the TTN indoor Gateway. Because it was cheap. 
How could we get help here? I think also perhaps you can share your experience with TTN

**Comment by OstertagM** [comment]
It worked now. I updated the complete lib.
I'll observe the problem.
