### ISSUE TITLE
Add heltec-automation-docs.readthedocs.io to READ.me

### ISSUE THREAD

**Issue by lnlp** [HelTecAutomation/ASR650x-Arduino#56]
A link to documentation [heltec-automation-docs.readthedocs.io](https://heltec-automation-docs.readthedocs.io/en/latest/cubecell/index.html) is missing from [READ.me](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/README.md) and should be added.

**Comment by Heltec-Aaron-Lee** [comment]
Thank you for your suggestions, I had added.
