### ISSUE TITLE
Some information in HTCC-AB01 circuit diagram (and possibly in FAQ) is incorrect

### ISSUE THREAD

**Issue by lnlp** [HelTecAutomation/ASR650x-Arduino#57]
In FAQ article [how-to-use-the-adc-pin-for-analogread-asr6501](https://docs.heltec.cn/#/en/faq/cubecell_series_common_problem_summary?id=how-to-use-the-adc-pin-for-analogread-asr6501) the following is mentioned:

> The ASR6501 embedded 12-bit 1Msps SAR ADC, but only have one channel ADC input pin, this pin had been used for battery voltage reading default.
> 
> In order to read other analog signal, user need remove the resistance BR1, then the ADC header will be free.

The name BR1 refers to a solder bridge which it is not because in reality this is a resistor (probably 0 ohm) it is not a solder bridge and without the board [IMAGE ](https://docs.heltec.cn/en/faq/img/cubecelladcbridge.png)in the FAQ one would never know where to find it.

In the [HTCC-AB01 circuit diagram](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/BlockDiagram/HT-AB01.pdf) this resistor is incorrectly drawn with a solder bridge symbol and named as a solder bridge (BR) instead of a resistor (R). **The circuit diagram should be corrected**.
Or, even better: make it a real solder bridge instead of a resistor in the next revision of the board.

The bridge/resistor should be labeled on the PCB silk screen but currently is not.

On my board resistor 'BR1' is missing which conflicts with the information in the FAQ. The FAQ says that the resistor is installed by default.

Is the **missing (0 Ohm) resistor 'BR1'** on my board an incident or is this a structural production change?
**If structural change** then the information in **the** [**FAQ** ](https://docs.heltec.cn/#/en/faq/cubecell_series_common_problem_summary?id=how-to-use-the-adc-pin-for-analogread-asr6501) is incorrect and **should be updated**.

**Comment by raystream** [comment]
in the block diagram there is a 0R beneath BR1 label.
it is shown as solder bridge because it is a "switch" but the 0R indicates that it is produced as a 0Ohm resistor on the pcb for easier manufacturing.

**Comment by lnlp** [comment]
It is inconsistent from whatever perspective you look at it, which is bad and confusing.
It should be fixed, one way or the other. Either in the circuit diagram or on the PCB and it should be added to the silkscreen.

**Comment by Heltec-Aaron-Lee** [comment]
Hi @lnlp 

The main reason is for easier manufacturing. I will fix the release version diagram.
