### ISSUE TITLE
HT-AC01 block diagram

### ISSUE THREAD

**Issue by grahamehorner** [HelTecAutomation/ASR650x-Arduino#61]
I'm unable to find the block diagram for the Capsule (I'm assuming it's called HT-AC01 give the naming of other diagrams etc.) is this available? if so where can it be located?

**Comment by wasn-eu** [comment]
right now there is no such diagram, but it is almost the same as the devboard except the USB to serial converter

**Comment by Heltec-Aaron-Lee** [comment]
Just added.
[https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/BlockDiagram/Capsule/Capsule_MCU.pdf](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/BlockDiagram/Capsule/Capsule_MCU.pdf)
