### ISSUE TITLE
CPU Frequency not set "F_CPU" : suggestion on boards.txt and platform.txt

### ISSUE THREAD

**Issue by fredolaredo** [HelTecAutomation/ASR650x-Arduino#63]
### Context:

needed for some libraries as the SoftwareSerial (which is not yet implemented by the way)

### boards.txt

> **menu.CPUFreq=CPU Frequency**
> menu.LORAWAN_REGION=LORAWAN_REGION
> menu.LORAWAN_CLASS=LORAWAN_CLASS
> menu.LORAWAN_NETMODE=LORAWAN_NETMODE
> menu.LORAWAN_ADR=LORAWAN_ADR
> menu.LORAWAN_Net_Reserve=LORAWAN_Net_Reservation
> menu.LORAWAN_AT_SUPPORT=LORAWAN_AT_SUPPORT
> menu.LORAWAN_RGB=LORAWAN_RGB
> ##############################################################
> 
> CubeCell-Board.name=CubeCell-Board
> 
> 
> **CubeCell-Board.menu.CPUFreq.48=48 MHz
> CubeCell-Board.menu.CPUFreq.48.build.f_cpu=48000000L**

### platform.txt

> ## Compile c files
> recipe.c.o.pattern="{compiler.path}{compiler.c.cmd}"  {compiler.cpreprocessor.flags}  {compiler.c.flags} **-DF_CPU={build.f_cpu}** {compiler.c.extra_flags}  {includes} "{source_file}" -o "{object_file}"
> 
> 
> ## Compile c++ files
> recipe.cpp.o.pattern="{compiler.path}{compiler.cpp.cmd}"  {compiler.cpreprocessor.flags} {compiler.cpp.flags} **-DF_CPU={build.f_cpu}** {compiler.cpp.extra_flags}  {includes} "{source_file}" -o "{object_file}"

**Comment by Heltec-Aaron-Lee** [comment]
As I know, the ASR6501 only has 48MHz one working frequency... anyway, I will look into the datasheet.

I had updated a software serial library: [https://github.com/HelTecAutomation/ASR650x-Arduino/tree/master/libraries/Basics/examples/softwareSerial](https://github.com/HelTecAutomation/ASR650x-Arduino/tree/master/libraries/Basics/examples/softwareSerial)
