### ISSUE TITLE
Save and restore sessions secures after the first join

### ISSUE THREAD

**Issue by OstertagM** [HelTecAutomation/ASR650x-Arduino#67]
How can I save the session secrets in ee prom and restore it? I don't want to do an ttn rejoin after complete loose of power.

**Comment by Heltec-Aaron-Lee** [comment]
Just keep this option ON.
![image](https://user-images.githubusercontent.com/32860565/74587859-a2e93200-5032-11ea-898f-35433d5569f5.png)

**Comment by Heltec-Aaron-Lee** [comment]
BTW. This document may make sense to you:
[https://heltec-automation-docs.readthedocs.io/en/latest/cubecell/quick_start.html](https://heltec-automation-docs.readthedocs.io/en/latest/cubecell/quick_start.html)

![image](https://user-images.githubusercontent.com/32860565/74587895-0d9a6d80-5033-11ea-8f6d-c4afeb9834ea.png)

**Comment by OstertagM** [comment]
Thanks a lot.

**Comment by OstertagM** [comment]
> Enable LORAWAN_Net_Reservation must disable Frame counter (fCnt) in LoRa server.
I think frame counts could also be safed and used again. What happens if I do not deactivate it? With what frame count starts after reset? Sorry for asking I can't test it at moment.

**Comment by OstertagM** [comment]
IS NOT working see now post:
https://github.com/HelTecAutomation/ASR650x-Arduino/issues/32

**Comment by Heltec-Aaron-Lee** [comment]
On the CubeCell board, there doesn't have an EEPROM, so the OTAA related parameters and keys are directly stored in FLASH. The number of flash reads and writes is often less than 100,000. If each downlink is stored, this will seriously reduce the life of the flash. So we store it every 15,000 times, which is why fCnt is turned off.

**Comment by OstertagM** [comment]
OK so if I connect to an EEProm external and write read here it would work!
But why did net reservation not work?

**Comment by Heltec-Aaron-Lee** [comment]
You need to make sure the node has successfully received last downlink message.

**Comment by OstertagM** [comment]
I know. But als there is a gap for missing some downlink.
The important is that I can send only f.e. Each 100 an confirmed one and the other a unconfirmed is that possible?

**Comment by Heltec-Aaron-Lee** [comment]
Which LoRa server did you use? Can you please upload your global_conf.json file? I think the problem is because of you gateway have a different listening frequency with CubeCell sending frequency.

**Comment by OstertagM** [comment]
I use TTN and it's indoor Gateway. So I don't have this file. And what has your answer todo with my question? I want to know why the node doesn't save keys if net reserve is on? And if I can send uplink confirmed and unconfirmed in same sketch?

**Comment by Heltec-Aaron-Lee** [comment]
I had just tested and confirmed at my side, the keys save at my side, there are two important keys to success:
- must have at least one success downlink message from LoRa server (Joined can't be);
- Must disable fCnt (Frame counter) in the server.

No, only confirmed or unconfirmed in the same sketch.

**Comment by OstertagM** [comment]
You know where is limitation on downlink in TTN. So I can do not always sending a confirmed uplink! Please provide a possibility in your lib to switch on confirmed for one uplink!

**Comment by Heltec-Aaron-Lee** [comment]
That's very easy...

when you received the first downlink message (by judge the fCnt), just set the `isTxConfirmed` to `false` by software.
![image](https://user-images.githubusercontent.com/32860565/75227565-5eefed00-57e9-11ea-9219-8afa05c74e8c.png)
