### ISSUE TITLE
RGB support

### ISSUE THREAD

**Issue by dbuggz** [HelTecAutomation/ASR650x-Arduino#70]
I'm using the CubeCell (HTCC_AB01) and the RGB example fails as follows:

_In file included from C:\Users\Dave\Documents\Arduino\hardware\CubeCell\ASR650x-Arduino\libraries\RGB\examples\RGB\RGB.ino:1:0:

C:\Users\Dave\Documents\Arduino\libraries\Adafruit_NeoPixel/Adafruit_NeoPixel.h: In member function 'boolean Adafruit_NeoPixel::canShow() const':

C:\Users\Dave\Documents\Arduino\libraries\Adafruit_NeoPixel/Adafruit_NeoPixel.h:234:58: error: 'micros' was not declared in this scope_

seems that 'micros' has not been defined for the CubeCell Core

**Comment by dbuggz** [comment]
This looks like issue #54. please add my request there.

**Comment by Heltec-Aaron-Lee** [comment]
![image](https://user-images.githubusercontent.com/32860565/76074051-ac344180-5fd5-11ea-9102-e8c9c3ee8ad4.png)

I can compile at my side... how did you install the framework?

**Comment by dbuggz** [comment]
Aaron,

i found it was using the Adafruit library, but complied OK with your library. Why is the Cubecell library different to the Adafruit one?
Dave

**Comment by Heltec-Aaron-Lee** [comment]
Hi @dbuggz
I had just added two examples, maybe that's the answer. :D
[https://github.com/HelTecAutomation/ASR650x-Arduino/issues/54#issuecomment-599449437](https://github.com/HelTecAutomation/ASR650x-Arduino/issues/54#issuecomment-599449437)

**Comment by dbuggz** [comment]
Thanks Aaron
