### ISSUE TITLE
Battery level Measurement without external component

### ISSUE THREAD

**Issue by nidaas** [HelTecAutomation/ASR650x-Arduino#73]
Hi, Is there  a way to measure MCU voltage without any external component.? Voltage level OE interrupt of low voltage also works in my application.
Thank You
Nidaas

**Comment by Heltec-Aaron-Lee** [comment]
there already have a battery voltage reading circuit on board, did you try with this example?
[https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/libraries/Basics/examples/ADC_battery/ADC_battery.ino](https://github.com/HelTecAutomation/ASR650x-Arduino/blob/master/libraries/Basics/examples/ADC_battery/ADC_battery.ino)

**Comment by nidaas** [comment]
Thanks for your response. I did and it works.
But I want to use this ADC pin for different purpose. So I wanted a way to measure internal Voltage like we can do in arduino, without any external GPIO pin.

**Comment by Heltec-Aaron-Lee** [comment]
Do you mean the PVD function for STM32? As I know, ASR6501 doesn't have such a function.

**Comment by Heltec-Aaron-Lee** [comment]
ASR6502 will be release soon, the ASR6502 series will have 3 ADC pins.

**Comment by nidaas** [comment]
ok thanks ASR6501 doesn't have feature of monitor battery with internal component only.
