### ISSUE TITLE
please add library for BMP280

### ISSUE THREAD

**Issue by raystream** [HelTecAutomation/ASR650x-Arduino#8]
Hello,

i have added a library for the BMP280 sensor and an example for a MJMCU-8128 Sensor board.
This sensor board include an HDC1080, CCS811 and BMP280

**Comment by Heltec-Aaron-Lee** [comment]
examples with the sensors you are using already here: [https://github.com/HelTecAutomation/ASR650x-Arduino/tree/master/libraries](https://github.com/HelTecAutomation/ASR650x-Arduino/tree/master/libraries)

![image](https://user-images.githubusercontent.com/32860565/67647197-5509ca80-f96c-11e9-9326-eb62abb98b36.png)

We don't have a BMP280 sensor example now. But you can refer to the BMP180 example.

**Comment by raystream** [comment]
I know that is why i have added a bmp280 library and an example in my fork

**Comment by Heltec-Aaron-Lee** [comment]
Thanks for your work. I added.
