### ISSUE TITLE
MAIN HELTEC WEBSITE DOWN

### ISSUE THREAD

**Issue by sivaelid** [HelTecAutomation/ASR650x-Arduino#87]
Main Website Pointed to wrong location and  SSL not valid

**Comment by wasn-eu** [comment]
![image](https://user-images.githubusercontent.com/6542516/80747590-fcd2a180-8b23-11ea-9e8a-5c7fe13bfd59.png)


your site is only reachable from china.
i have tested it from the usa and europe all with the same result as shown for munich

**Comment by wasn-eu** [comment]
your new ip has not been propagated to US and European DNS Servers.

**Comment by Heltec-Aaron-Lee** [comment]
Hi there, thanks for your feedback.

Previously because of the conflict between the global acceleration configuration and the SSL certificate, it has now been corrected.
