### ISSUE TITLE
pins_arduino?

### ISSUE THREAD

**Issue by Skipper-is** [HelTecAutomation/ASR650x-Arduino#9]
I'm using the CubeCell Board, is there a pin definition file for the board? For example the ESP32 Heltec modules have a pin_arduino.h file that has the pin definitions - So A0 is pin 36, SS is 18. Is there one for the CubeCell? I can't seem to find one

**Comment by Heltec-Aaron-Lee** [comment]
Yeah, currently we still not add such support. you need to use GPIO0 or GPIO1 etc.

I will update fully Arduino pin support today.
