### ISSUE TITLE
Any news on the platform.io support?

### ISSUE THREAD

**Issue by synth3** [HelTecAutomation/ASR650x-Arduino#90]
Hi there, are there any news regarding the platform.io support for this board? :)

**Comment by lyusupov** [comment]
https://github.com/HelTecAutomation/platform-asrmicro

**Comment by lnlp** [comment]
This is a duplicate of issue #11 and should therefore be closed.

@synth3 Check open issues first and do not post duplicates.

**Comment by synth3** [comment]
Thanks and sorry for not searching the issues properly! :)
