### ISSUE TITLE
MAC and PHY version

### ISSUE THREAD

**Issue by wasn-eu** [HelTecAutomation/ASR650x-Arduino#92]
Hello,

to configure The Things Stack i need to know the MAC and PHY version.
the website stated a MAC version of 1.0.2 but no PHY version.

If i select version 1.0.2 for both in the things stack i can only receive packet which are send on channel index 0,1 and 2
The same node is sending fine on all channels to ttn and a chirpstack

**Comment by Heltec-Aaron-Lee** [comment]
The MAC version: Migration from LoRaMac-Node 4.4.0, LoRaWAN protocol 1.0.2, regional parameter V1.0.2 rB

PHY: use SX1262 as the PHY cheap
