### ISSUE TITLE
README.md needs to be updated

### ISSUE THREAD

**Issue by lnlp** [HelTecAutomation/ASR650x-Arduino#93]
> MCU | Relative boards
> -- | --
> ASR6501 | CubeCell-Board, CubeCell-Module, CubeCell-Cupsule
> ASR6502 | Coming soon

ASR6502 based CubeCell products have been released. 
README.md needs to be updated accordingly.

**Comment by wasn-eu** [comment]
updated readme.md
https://github.com/HelTecAutomation/ASR650x-Arduino/commit/06abcbc568a1ca5f6b94c6e7c0be37e670f5af6d
