### ISSUE TITLE
Title of HTCC-AB02S pinout diagram is incorrect

### ISSUE THREAD

**Issue by lnlp** [HelTecAutomation/ASR650x-Arduino#96]
As the pinout diagram resource is external to GitHub, but relevant to both this repository and https://github.com/HelTecAutomation/HeltecDocs, I add it as an issue here.

The title of the [HTCC-AB02S pinout diagram](https://resource.heltec.cn/download/CubeCell/HTCC-AB02S/HTCC-AB02S_PinoutDiagram.pdf) is incorrect.

It incorrectly says "CubeCell HTCC-AB02 Pinout Diagram" which should be:

**CubeCell HTCC-AB02S Pinout Diagram**

**Comment by wasn-eu** [comment]
fixed
